name: linter-check

on: [push]

jobs:
  linter-check:
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: pypy3

    steps:
        -name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
        -name: Lint with flake8
        run: |
          pip install flake8
          make lint
        continue-on-error: true